---
upload_path: "/site/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/secret-admin"
webhook_url: 
sections:
  docs:
    default_front_matter_template: docs
  blog:
    default_front_matter_template: blog
version: 0.38.1
